import * as vscode from 'vscode';
import { QueryExecutionResult } from '../types';

function escapeHtml(value: unknown): string {
  const text = String(value ?? '');
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function renderCell(value: unknown): string {
  if (value === null) {
    return '<span class="null">NULL</span>';
  }

  if (typeof value === 'object') {
    return `<pre>${escapeHtml(JSON.stringify(value, null, 2))}</pre>`;
  }

  return escapeHtml(value);
}

interface RenderState {
  connectionName: string;
  sql: string;
  result: QueryExecutionResult;
}

export class ResultsPanel implements vscode.WebviewViewProvider {
  static readonly viewId = 'dbInspector.resultsView';
  static readonly panelContainerCommand = 'workbench.view.extension.dbInspectorResults';

  private view: vscode.WebviewView | undefined;
  private latest: RenderState | undefined;
  private showStatus = false;
  private showQuery = false;

  async show(connectionName: string, sql: string, result: QueryExecutionResult): Promise<void> {
    this.latest = {
      connectionName,
      sql,
      result,
    };

    await vscode.commands.executeCommand(ResultsPanel.panelContainerCommand);

    // Focus command is generated by VS Code for contributed views.
    await vscode.commands.executeCommand(`${ResultsPanel.viewId}.focus`).then(
      () => undefined,
      () => undefined,
    );

    this.render();
  }

  resolveWebviewView(webviewView: vscode.WebviewView): void {
    this.view = webviewView;

    this.view.onDidDispose(() => {
      if (this.view === webviewView) {
        this.view = undefined;
      }
    });

    this.render();
  }

  toggleStatus(): void {
    this.showStatus = !this.showStatus;
    this.render();
  }

  toggleQuery(): void {
    this.showQuery = !this.showQuery;
    this.render();
  }

  private render(): void {
    if (!this.view) {
      return;
    }

    if (!this.latest) {
      this.view.webview.html = this.renderEmptyHtml();
      return;
    }

    this.view.webview.html = this.renderHtml(
      this.latest.connectionName,
      this.latest.sql,
      this.latest.result,
    );
  }

  private renderEmptyHtml(): string {
    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style>
          body {
            margin: 0;
            padding: 16px;
            font-family: var(--vscode-font-family);
            color: var(--vscode-foreground);
          }

          .hint {
            color: var(--vscode-descriptionForeground);
            font-style: italic;
          }
        </style>
      </head>
      <body>
        <div class="hint">Run a SQL query to show results here.</div>
      </body>
      </html>
    `;
  }

  private renderHtml(connectionName: string, sql: string, result: QueryExecutionResult): string {
    const rowsHtml = result.rows
      .map((row) => {
        const cells = result.columns
          .map((column) => `<td>${renderCell((row as Record<string, unknown>)[column])}</td>`)
          .join('');

        return `<tr>${cells}</tr>`;
      })
      .join('');

    const columnsHtml = result.columns.map((column) => `<th>${escapeHtml(column)}</th>`).join('');

    const body = result.columns.length
      ? `
        <div class="table-container">
          <table>
            <thead>
              <tr>${columnsHtml}</tr>
            </thead>
            <tbody>
              ${rowsHtml || `<tr><td colspan="${result.columns.length}"><span class="empty">No rows returned.</span></td></tr>`}
            </tbody>
          </table>
        </div>
      `
      : `<p class="empty">${escapeHtml(result.message ?? 'Statement completed.')}</p>`;

    const statusBlock = this.showStatus
      ? `
        <div class="status-strip">
          <span><strong>Connection:</strong> ${escapeHtml(connectionName)}</span>
          <span><strong>Rows:</strong> ${result.rowCount}</span>
          <span><strong>Duration:</strong> ${result.durationMs} ms</span>
          ${result.message ? `<span><strong>Message:</strong> ${escapeHtml(result.message)}</span>` : ''}
        </div>
      `
      : '';

    const queryBlock = this.showQuery
      ? `
        <div class="query-block">
          <pre>${escapeHtml(sql.trim())}</pre>
        </div>
      `
      : '';

    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>DB Inspector Results</title>
        <style>
          :root {
            color-scheme: light dark;
          }

          * {
            box-sizing: border-box;
          }

          html,
          body {
            margin: 0;
            font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace;
            padding: 12px;
            height: 100vh;
          }

          body {
            display: flex;
            flex-direction: column;
            overflow: hidden;
          }

          .status-strip {
            margin-bottom: 10px;
            border: 1px solid var(--vscode-widget-border);
            border-radius: 6px;
            background: var(--vscode-editor-background);
            padding: 8px 10px;
            color: var(--vscode-descriptionForeground);
            font-size: 12px;
            display: flex;
            flex-wrap: wrap;
            gap: 12px;
          }

          .query-block {
            border: 1px solid var(--vscode-widget-border);
            border-radius: 6px;
            background: var(--vscode-textCodeBlock-background);
            padding: 10px;
            margin-bottom: 10px;
            font-size: 12px;
          }

          .query-block pre {
            margin: 0;
            white-space: pre-wrap;
            word-break: break-word;
          }

          .table-container {
            border: 1px solid var(--vscode-widget-border);
            border-radius: 6px;
            overflow: auto;
            flex: 1;
            min-height: 0;
          }

          table {
            border-collapse: collapse;
            width: max-content;
            min-width: 100%;
          }

          th,
          td {
            border-bottom: 1px solid var(--vscode-editorWidget-border);
            text-align: left;
            padding: 8px 10px;
            vertical-align: top;
            max-width: 360px;
            overflow-wrap: break-word;
            white-space: pre-wrap;
          }

          th {
            position: sticky;
            top: 0;
            background: var(--vscode-editorGroupHeader-tabsBackground);
            z-index: 2;
          }

          tr:nth-child(even) td {
            background: color-mix(in srgb, var(--vscode-editor-background) 94%, var(--vscode-list-hoverBackground));
          }

          .null {
            color: var(--vscode-symbolIcon-colorForeground);
            font-style: italic;
          }

          .empty {
            color: var(--vscode-descriptionForeground);
            font-style: italic;
          }

          pre {
            margin: 0;
          }
        </style>
      </head>
      <body>
        ${statusBlock}
        ${queryBlock}
        ${body}
      </body>
      </html>
    `;
  }
}
