import * as vscode from 'vscode';
import { QueryExecutionResult } from '../types';

function escapeHtml(value: unknown): string {
  const text = String(value ?? '');
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function renderCell(value: unknown): string {
  if (value === null) {
    return '<span class="null">NULL</span>';
  }

  if (typeof value === 'object') {
    return `<pre>${escapeHtml(JSON.stringify(value, null, 2))}</pre>`;
  }

  return escapeHtml(value);
}

interface RenderState {
  connectionName: string;
  sql: string;
  result: QueryExecutionResult;
}

interface RunSandboxQueryMessage {
  type: 'runSandboxQuery';
  sql?: unknown;
}

interface RequestCompletionsMessage {
  type: 'requestCompletions';
  requestId?: unknown;
  sql?: unknown;
  cursor?: unknown;
}

type ResultsPanelMessage = RunSandboxQueryMessage | RequestCompletionsMessage;

export interface SandboxCompletionItem {
  label: string;
  detail?: string;
  insertText: string;
}

interface ResultsPanelOptions {
  onRunSandboxQuery: (sql: string) => Promise<void>;
  onRequestCompletions: (sql: string, cursor: number) => Promise<SandboxCompletionItem[]>;
  getCurrentConnectionName: () => string | undefined;
}

export class ResultsPanel implements vscode.WebviewViewProvider {
  static readonly viewId = 'dbInspector.resultsView';
  static readonly panelContainerCommand = 'workbench.view.extension.dbInspectorResults';
  private static readonly hasResultsContextKey = 'dbInspector.resultsHasData';

  private view: vscode.WebviewView | undefined;
  private latest: RenderState | undefined;
  private showStatus = false;
  private showQuery = false;

  constructor(private readonly options: ResultsPanelOptions) {}

  async show(connectionName: string, sql: string, result: QueryExecutionResult): Promise<void> {
    this.latest = {
      connectionName,
      sql,
      result,
    };

    await vscode.commands.executeCommand(ResultsPanel.panelContainerCommand);

    // Focus command is generated by VS Code for contributed views.
    await vscode.commands.executeCommand(`${ResultsPanel.viewId}.focus`).then(
      () => undefined,
      () => undefined,
    );

    this.render();
  }

  clear(): void {
    this.latest = undefined;
    this.updateHasResultsContext(false);
    this.render();
  }

  getLatest(): RenderState | undefined {
    return this.latest;
  }

  resolveWebviewView(webviewView: vscode.WebviewView): void {
    this.view = webviewView;
    this.view.webview.options = {
      enableScripts: true,
      enableCommandUris: true,
    };

    this.view.webview.onDidReceiveMessage((message: ResultsPanelMessage) => {
      void this.onDidReceiveMessage(message);
    });

    this.view.onDidDispose(() => {
      if (this.view === webviewView) {
        this.view = undefined;
      }
    });

    this.render();
  }

  toggleStatus(): void {
    this.showStatus = !this.showStatus;
    this.render();
  }

  toggleQuery(): void {
    this.showQuery = !this.showQuery;
    this.render();
  }

  private async onDidReceiveMessage(message: ResultsPanelMessage): Promise<void> {
    if (message?.type === 'runSandboxQuery') {
      const sql = typeof message.sql === 'string' ? message.sql.trim() : '';
      if (!sql) {
        void vscode.window.showWarningMessage('No SQL to run.');
        return;
      }

      await this.options.onRunSandboxQuery(sql);
      return;
    }

    if (message?.type !== 'requestCompletions') {
      return;
    }

    const requestId = typeof message.requestId === 'number' ? message.requestId : undefined;
    if (requestId === undefined || !this.view) {
      return;
    }

    const sql = typeof message.sql === 'string' ? message.sql : '';
    const rawCursor = typeof message.cursor === 'number' ? message.cursor : sql.length;
    const cursor = Math.max(0, Math.min(sql.length, rawCursor));

    try {
      const items = await this.options.onRequestCompletions(sql, cursor);
      await this.view.webview.postMessage({
        type: 'completions',
        requestId,
        items,
      });
    } catch {
      await this.view.webview.postMessage({
        type: 'completions',
        requestId,
        items: [],
      });
    }
  }

  private render(): void {
    this.updateHasResultsContext(Boolean(this.latest));

    if (!this.view) {
      return;
    }

    if (!this.latest) {
      this.view.webview.html = this.renderEmptyHtml();
      return;
    }

    this.view.webview.html = this.renderHtml(
      this.latest.connectionName,
      this.latest.sql,
      this.latest.result,
    );
  }

  private updateHasResultsContext(hasResults: boolean): void {
    void vscode.commands.executeCommand('setContext', ResultsPanel.hasResultsContextKey, hasResults);
  }

  private renderEmptyHtml(): string {
    const connectionName = this.options.getCurrentConnectionName();
    const connectionLabel = connectionName
      ? `Active connection: <strong>${escapeHtml(connectionName)}</strong>`
      : 'No active connection. You can still run SQL and choose a connection.';

    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style>
          :root {
            color-scheme: light dark;
          }

          * {
            box-sizing: border-box;
          }

          html,
          body {
            margin: 0;
            padding: 16px;
            font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace;
            color: var(--vscode-foreground);
            height: 100%;
          }

          body {
            display: flex;
            flex-direction: column;
            justify-content: center;
          }

          .card {
            border: 1px solid var(--vscode-widget-border);
            border-radius: 6px;
            background: var(--vscode-editor-background);
            padding: 12px;
            display: flex;
            flex-direction: column;
            gap: 10px;
          }

          .hint {
            color: var(--vscode-descriptionForeground);
            font-size: 12px;
            line-height: 1.4;
          }

          textarea {
            width: 100%;
            min-height: 108px;
            border: 1px solid var(--vscode-input-border);
            border-radius: 4px;
            background: var(--vscode-input-background);
            color: var(--vscode-input-foreground);
            padding: 8px;
            font-family: inherit;
            resize: vertical;
          }

          .actions {
            display: flex;
            align-items: center;
            gap: 10px;
            flex-wrap: wrap;
          }

          .editor-wrap {
            position: relative;
          }

          .autocomplete-menu {
            position: absolute;
            left: 0;
            right: auto;
            top: calc(100% + 4px);
            min-width: 360px;
            max-width: min(680px, 92vw);
            max-height: 220px;
            overflow: auto;
            border: 1px solid var(--vscode-widget-border);
            border-radius: 6px;
            background: var(--vscode-editorWidget-background);
            box-shadow: 0 8px 24px rgba(0, 0, 0, 0.25);
            z-index: 20;
            display: none;
          }

          .autocomplete-menu.visible {
            display: block;
          }

          .autocomplete-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 12px;
            width: 100%;
            border: none;
            border-bottom: 1px solid var(--vscode-editorWidget-border);
            background: transparent;
            color: var(--vscode-foreground);
            font-family: inherit;
            text-align: left;
            padding: 6px 10px;
            cursor: pointer;
          }

          .autocomplete-item:last-child {
            border-bottom: none;
          }

          .autocomplete-item.active {
            background: var(--vscode-list-activeSelectionBackground);
            color: var(--vscode-list-activeSelectionForeground);
          }

          .autocomplete-detail {
            color: var(--vscode-descriptionForeground);
            font-size: 11px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
          }

          button {
            border: none;
            border-radius: 4px;
            background: var(--vscode-button-background);
            color: var(--vscode-button-foreground);
            padding: 6px 12px;
            cursor: pointer;
            font-family: inherit;
          }

          button:hover {
            background: var(--vscode-button-hoverBackground);
          }

          .secondary {
            color: var(--vscode-descriptionForeground);
            text-decoration: none;
            font-size: 12px;
          }

          .secondary:hover {
            text-decoration: underline;
          }
        </style>
      </head>
      <body>
        <div class="card">
          <div class="hint">Run a SQL query to show results here.</div>
          <div class="hint">${connectionLabel}</div>
          <div class="editor-wrap">
            <textarea id="sandbox-query" spellcheck="false" placeholder="SELECT 1;"></textarea>
            <div id="autocomplete-menu" class="autocomplete-menu"></div>
          </div>
          <div class="actions">
            <button id="run-query" type="button">Run Query</button>
            <a class="secondary" href="command:dbInspector.openQueryEditor">Open SQL Editor</a>
          </div>
        </div>
        <script>
          const vscode = acquireVsCodeApi();
          const input = document.getElementById('sandbox-query');
          const runButton = document.getElementById('run-query');
          const menu = document.getElementById('autocomplete-menu');
          let completionItems = [];
          let selectedCompletionIndex = 0;
          let completionRequestId = 0;
          let latestCompletionRequestId = 0;
          let completionTimer;

          const closeCompletions = () => {
            completionItems = [];
            selectedCompletionIndex = 0;
            menu.classList.remove('visible');
            menu.innerHTML = '';
          };

          const currentPrefixRange = () => {
            const cursor = input.selectionStart ?? 0;
            let start = cursor;
            while (start > 0 && /[A-Za-z0-9_]/.test(input.value[start - 1])) {
              start -= 1;
            }
            return { start, end: cursor };
          };

          const applyCompletion = (item) => {
            const range = currentPrefixRange();
            const before = input.value.slice(0, range.start);
            const after = input.value.slice(range.end);
            input.value = before + item.insertText + after;
            const newCursor = before.length + item.insertText.length;
            input.focus();
            input.selectionStart = newCursor;
            input.selectionEnd = newCursor;
            closeCompletions();
          };

          const renderCompletions = () => {
            if (!completionItems.length) {
              closeCompletions();
              return;
            }

            menu.innerHTML = completionItems
              .map((item, index) => {
                const activeClass = index === selectedCompletionIndex ? 'active' : '';
                const detail = item.detail ? '<span class="autocomplete-detail">' + item.detail + '</span>' : '';
                return '<button type="button" class="autocomplete-item ' + activeClass + '" data-index="' + index + '"><span>' + item.label + '</span>' + detail + '</button>';
              })
              .join('');

            menu.classList.add('visible');
          };

          const requestCompletions = () => {
            const cursor = input.selectionStart ?? input.value.length;
            completionRequestId += 1;
            latestCompletionRequestId = completionRequestId;
            vscode.postMessage({
              type: 'requestCompletions',
              requestId: completionRequestId,
              sql: input.value,
              cursor
            });
          };

          const scheduleCompletions = (delay = 120) => {
            clearTimeout(completionTimer);
            completionTimer = setTimeout(requestCompletions, delay);
          };

          const run = () => {
            vscode.postMessage({
              type: 'runSandboxQuery',
              sql: input.value
            });
          };

          runButton.addEventListener('click', run);
          input.addEventListener('input', () => {
            scheduleCompletions();
          });
          input.addEventListener('keydown', (event) => {
            if (menu.classList.contains('visible')) {
              if (event.key === 'ArrowDown') {
                event.preventDefault();
                selectedCompletionIndex = (selectedCompletionIndex + 1) % completionItems.length;
                renderCompletions();
                return;
              }

              if (event.key === 'ArrowUp') {
                event.preventDefault();
                selectedCompletionIndex =
                  (selectedCompletionIndex - 1 + completionItems.length) % completionItems.length;
                renderCompletions();
                return;
              }

              if (event.key === 'Enter' || event.key === 'Tab') {
                event.preventDefault();
                applyCompletion(completionItems[selectedCompletionIndex]);
                return;
              }

              if (event.key === 'Escape') {
                event.preventDefault();
                closeCompletions();
                return;
              }
            }

            if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') {
              event.preventDefault();
              run();
              return;
            }

            if ((event.metaKey || event.ctrlKey) && event.key === ' ') {
              event.preventDefault();
              requestCompletions();
            }
          });

          input.addEventListener('blur', () => {
            setTimeout(() => closeCompletions(), 120);
          });

          input.addEventListener('focus', () => {
            scheduleCompletions(60);
          });

          menu.addEventListener('mousedown', (event) => {
            const target = event.target.closest('.autocomplete-item');
            if (!target) {
              return;
            }

            event.preventDefault();
            const index = Number(target.dataset.index);
            if (!Number.isInteger(index) || !completionItems[index]) {
              return;
            }

            applyCompletion(completionItems[index]);
          });

          window.addEventListener('message', (event) => {
            const data = event.data;
            if (!data || data.type !== 'completions') {
              return;
            }
            if (data.requestId !== latestCompletionRequestId) {
              return;
            }

            completionItems = Array.isArray(data.items) ? data.items : [];
            selectedCompletionIndex = 0;
            renderCompletions();
          });
        </script>
      </body>
      </html>
    `;
  }

  private renderHtml(connectionName: string, sql: string, result: QueryExecutionResult): string {
    const rowsHtml = result.rows
      .map((row) => {
        const cells = result.columns
          .map((column) => `<td>${renderCell((row as Record<string, unknown>)[column])}</td>`)
          .join('');

        return `<tr>${cells}</tr>`;
      })
      .join('');

    const columnsHtml = result.columns.map((column) => `<th>${escapeHtml(column)}</th>`).join('');

    const body = result.columns.length
      ? `
        <div class="table-container">
          <table>
            <thead>
              <tr>${columnsHtml}</tr>
            </thead>
            <tbody>
              ${rowsHtml || `<tr><td colspan="${result.columns.length}"><span class="empty">No rows returned.</span></td></tr>`}
            </tbody>
          </table>
        </div>
      `
      : `<p class="empty">${escapeHtml(result.message ?? 'Statement completed.')}</p>`;

    const statusBlock = this.showStatus
      ? `
        <div class="status-strip">
          <span><strong>Connection:</strong> ${escapeHtml(connectionName)}</span>
          <span><strong>Rows:</strong> ${result.rowCount}</span>
          <span><strong>Duration:</strong> ${result.durationMs} ms</span>
          ${result.message ? `<span><strong>Message:</strong> ${escapeHtml(result.message)}</span>` : ''}
        </div>
      `
      : '';

    const queryBlock = this.showQuery
      ? `
        <div class="query-block">
          <pre>${escapeHtml(sql.trim())}</pre>
        </div>
      `
      : '';

    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>DB Inspector Results</title>
        <style>
          :root {
            color-scheme: light dark;
          }

          * {
            box-sizing: border-box;
          }

          html,
          body {
            margin: 0;
            font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace;
            padding: 12px;
            height: 100vh;
          }

          body {
            display: flex;
            flex-direction: column;
            overflow: hidden;
          }

          .status-strip {
            margin-bottom: 10px;
            border: 1px solid var(--vscode-widget-border);
            border-radius: 6px;
            background: var(--vscode-editor-background);
            padding: 8px 10px;
            color: var(--vscode-descriptionForeground);
            font-size: 12px;
            display: flex;
            flex-wrap: wrap;
            gap: 12px;
          }

          .query-block {
            border: 1px solid var(--vscode-widget-border);
            border-radius: 6px;
            background: var(--vscode-textCodeBlock-background);
            padding: 10px;
            margin-bottom: 10px;
            font-size: 12px;
          }

          .query-block pre {
            margin: 0;
            white-space: pre-wrap;
            word-break: break-word;
          }

          .table-container {
            border: 1px solid var(--vscode-widget-border);
            border-radius: 6px;
            overflow: auto;
            flex: 1;
            min-height: 0;
          }

          table {
            border-collapse: collapse;
            width: max-content;
            min-width: 100%;
          }

          th,
          td {
            border-bottom: 1px solid var(--vscode-editorWidget-border);
            text-align: left;
            padding: 8px 10px;
            vertical-align: top;
            max-width: 360px;
            overflow-wrap: break-word;
            white-space: pre-wrap;
          }

          th {
            position: sticky;
            top: 0;
            background: var(--vscode-editorGroupHeader-tabsBackground);
            z-index: 2;
          }

          tr:nth-child(even) td {
            background: color-mix(in srgb, var(--vscode-editor-background) 94%, var(--vscode-list-hoverBackground));
          }

          .null {
            color: var(--vscode-symbolIcon-colorForeground);
            font-style: italic;
          }

          .empty {
            color: var(--vscode-descriptionForeground);
            font-style: italic;
          }

          pre {
            margin: 0;
          }
        </style>
      </head>
      <body>
        ${statusBlock}
        ${queryBlock}
        ${body}
      </body>
      </html>
    `;
  }
}
